name: storystains
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter      
  json_annotation: ^4.6.0
  dio: ^4.0.6
  shared_preferences: ^2.0.12
  retrofit: '>=3.0.0 <4.0.0'
  flutter_markdown: ^0.6.10+3
  logger: ^1.1.0  #for logging purpose
  google_fonts: ^3.0.1
  cached_network_image: ^3.1.0+1
  scrollable_positioned_list: ^0.3.2
  equatable: ^2.0.3
  provider: ^6.0.1
  injectable: ^1.5.0
  get_it: ^7.2.0
  intl: ^0.17.0
  flutter_svg: ^1.1.0
  collection: ^1.16.0
  dio_cookie_manager: ^2.0.0 
  cookie_jar: ^3.0.1
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.11
  json_serializable: '>4.4.0'
  flutter_lints: ^2.0.1
  dependency_validator: ^3.0.0
  mockito: ^5.2.0
  dart_code_metrics: ^4.15.2
  http: ^0.13.4
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_ios: "assets/icons/icon.png"
  image_path: "assets/icons/logo_rounded_corners.png"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/lottie/
    - assets/fonts/
    - assets/images/
    - assets/icons/

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Domitian
      fonts:
        - asset: assets/fonts/Domitian-Roman.ttf