# fly.toml file generated for storystains on 2022-05-30T08:59:41+02:00
app = "storystains"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
APP_APPLICATION__BASE_URL = "https://storystains.fly.dev"
APP__FRONTEND_ORIGIN = "https://storystains.fly.dev"
APP_DATABASE__HOST = "top2.nearest.of.storystains-db.internal"
APP_DATABASE__PORT = "5432"
APP_DATABASE__DATABASE_NAME = "storystains"
APP_DATABASE__USERNAME = "storystains"
# Need the following to be secrets:
# APP_APPLICATION__HMAC_SECRET
# APP_DATABASE__PASSWORD

# DATABASE_URL??
[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[services.http_checks]]
interval = 10000
grace_period = "5s"
method = "get"
path = "/api/health_check"
protocol = "http"
restart_limit = 0
timeout = 2000
tls_skip_verify = false

# [[services.http_checks]]
# interval = 1000000
# grace_period = "5s"
# method = "get"
# path = "/api/db_check"
# protocol = "http"
# restart_limit = 0
# timeout = 2000
# tls_skip_verify = false
