# fly.toml file generated for storystains on 2022-05-30T08:59:41+02:00
app = "storystains"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
APP__APPLICATION__BASE_URL = "https://app.storystains.com"
APP__FRONTEND__ORIGIN = "https://app.storystains.com"
APP__DATABASE__HOST = "top2.nearest.of.storystains-db.internal"
APP__DATABASE__USERNAME = "storystains"
APP__DATABASE__REQUIRE_SSL = "false"
# Need the following to be secrets:
# APP__APPLICATION__HMAC_SECRET
# APP__DATABASE__PASSWORD
# APP__REDIS_URI

# DATABASE_URL??
[experimental]
allowed_public_ports = []
auto_rollback = true

[build.args]
FRONT_BASE_URL = "https://app.storystains.com/api"

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[services.http_checks]]
interval = 10000
grace_period = "5s"
method = "get"
path = "/api/health_check"
protocol = "http"
restart_limit = 0
timeout = 2000
tls_skip_verify = false

[[services.http_checks]]
interval = 1000000
grace_period = "5s"
method = "get"
path = "/api/db_check"
protocol = "http"
restart_limit = 0
timeout = 2000
tls_skip_verify = false


[metrics]
port = 9091
path = "/metrics"
