// Mocks generated by Mockito 5.2.0 from annotations
// in storystains/test/review.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:storystains/models/review.dart' as _i4;
import 'package:storystains/modules/review/review_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ReviewService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReviewService extends _i1.Mock implements _i2.ReviewService {
  MockReviewService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> add(_i4.EditReview? review) =>
      (super.noSuchMethod(Invocation.method(#add, [review]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> update(_i4.EditReview? review) =>
      (super.noSuchMethod(Invocation.method(#update, [review]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
}
