import 'package:flutter/material.dart';

const seed = Color(0xFF6750A4);

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF8E4F00),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFFFDCBD),
  onPrimaryContainer: Color(0xFF2D1600),
  secondary: Color(0xFF006685),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFBCE9FF),
  onSecondaryContainer: Color(0xFF001F2A),
  tertiary: Color(0xFF8F4E00),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFFFDCBF),
  onTertiaryContainer: Color(0xFF2E1500),
  error: Color(0xFFB3261E),
  errorContainer: Color(0xFFF9DEDC),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410E0B),
  background: Color(0xFFFFFBFE),
  onBackground: Color(0xFF1C1B1F),
  surface: Color(0xFFFFFBFE),
  onSurface: Color(0xFF1C1B1F),
  surfaceVariant: Color(0xFFE7E0EC),
  onSurfaceVariant: Color(0xFF49454F),
  outline: Color(0xFF79747E),
  onInverseSurface: Color(0xFFF4EFF4),
  inverseSurface: Color(0xFF313033),
  inversePrimary: Color(0xFFFFB772),
  shadow: Color(0xFF000000),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFFFB772),
  onPrimary: Color(0xFF4C2700),
  primaryContainer: Color(0xFF6C3A00),
  onPrimaryContainer: Color(0xFFFFDCBD),
  secondary: Color(0xFF65D3FF),
  onSecondary: Color(0xFF003547),
  secondaryContainer: Color(0xFF004D66),
  onSecondaryContainer: Color(0xFFBCE9FF),
  tertiary: Color(0xFFFFB775),
  onTertiary: Color(0xFF4D2700),
  tertiaryContainer: Color(0xFF6D3A00),
  onTertiaryContainer: Color(0xFFFFDCBF),
  error: Color(0xFFF2B8B5),
  errorContainer: Color(0xFF8C1D18),
  onError: Color(0xFF601410),
  onErrorContainer: Color(0xFFF9DEDC),
  background: Color(0xFF1C1B1F),
  onBackground: Color(0xFFE6E1E5),
  surface: Color(0xFF1C1B1F),
  onSurface: Color(0xFFE6E1E5),
  surfaceVariant: Color(0xFF49454F),
  onSurfaceVariant: Color(0xFFCAC4D0),
  outline: Color(0xFF938F99),
  onInverseSurface: Color(0xFF1C1B1F),
  inverseSurface: Color(0xFFE6E1E5),
  inversePrimary: Color(0xFF8E4F00),
  shadow: Color(0xFF000000),
);

ButtonStyle homeButtonStyle = OutlinedButton.styleFrom(
  padding: const EdgeInsets.symmetric(horizontal: 18),
  shape: RoundedRectangleBorder(
    borderRadius: BorderRadius.circular(8.0),
  ),
);
