start TRANSACTION;
ALTER TABLE emotions
ADD COLUMN joy INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN sadness INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN anger INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN disgust INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN fear INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN surprise INTEGER NOT NULL DEFAULT 0;
INSERT INTO emotions (
        id,
        name,
        description,
        icon_url,
        joy,
        sadness,
        anger,
        disgust,
        fear,
        surprise
    )
VALUES (
        1,
        'Anger',
        'Strong displeasure against a someone or something.',
        '/emotions/anger.svg',
        0,
        0,
        3,
        0,
        0,
        0
    ),
    (
        2,
        'Disgust',
        'An aversion to something distasteful.',
        '/emotions/disgust.svg',
        0,
        0,
        0,
        3,
        0,
        0
    ),
    (
        3,
        'Fear',
        'To expect danger.',
        '/emotions/fear.svg',
        0,
        0,
        0,
        0,
        3,
        0
    ),
    (
        4,
        'Joy',
        'Strong pleasure.',
        '/emotions/joy.svg',
        3,
        0,
        0,
        0,
        0,
        0
    ),
    (
        5,
        'Sadness',
        'Unhappiness.',
        '/emotions/sadness.svg',
        0,
        3,
        0,
        0,
        0,
        0
    ),
    (
        6,
        'Surprise',
        'Reaction to an unexpected event.',
        '/emotions/surprise.svg',
        0,
        0,
        0,
        0,
        0,
        3
    ),
    (
        7,
        'Outrage',
        'Combination of Anger and disgust.',
        '/emotions/outrage.svg',
        0,
        0,
        3,
        3,
        0,
        0
    ),
    (
        8,
        'Trapped',
        'Combination of Anger and Fear.',
        '/emotions/trapped.svg',
        0,
        0,
        3,
        0,
        3,
        0
    ),
    (
        9,
        'Cruelty',
        'Combination of Anger and Joy.',
        '/emotions/cruelty.svg',
        3,
        0,
        3,
        0,
        0,
        0
    ),
    (
        10,
        'Betrayal',
        'Combination of Anger and Sadness.',
        '/emotions/betrayal.svg',
        0,
        3,
        3,
        0,
        0,
        0
    ),
    (
        11,
        'What the?',
        'Combination of Anger and Surprise.',
        '/emotions/what-the.svg',
        0,
        0,
        3,
        0,
        0,
        3
    ),
    (
        12,
        'Horror',
        'Combination of Disgust and Fear.',
        '/emotions/horror.svg',
        0,
        0,
        0,
        3,
        3,
        0
    ),
    (
        13,
        'Eww',
        'Combination of Disgust and Joy.',
        '/emotions/eww.svg',
        3,
        0,
        0,
        3,
        0,
        0
    ),
    (
        14,
        'Pain Empathy',
        'Combination of Disgust and Sadness.',
        '/emotions/pain-empathy.svg',
        0,
        3,
        0,
        3,
        0,
        0
    ),
    (
        15,
        'You ate it!',
        'Combination of Disgust and Surprise.',
        '/emotions/you-ate-it.svg',
        0,
        0,
        0,
        3,
        0,
        3
    ),
    (
        16,
        'Desperation',
        'Combination of Fear and Joy.',
        '/emotions/desperation.svg',
        3,
        0,
        0,
        0,
        3,
        0
    ),
    (
        17,
        'Devastation',
        'Combination of Fear and Sadness.',
        '/emotions/devastation.svg',
        0,
        3,
        0,
        0,
        3,
        0
    ),
    (
        18,
        'Spooked',
        'Combination of Fear and Surprise.',
        '/emotions/spooked.svg',
        0,
        0,
        0,
        0,
        3,
        3
    ),
    (
        19,
        'Faint Hope',
        'Combination of Joy and Sadness.',
        '/emotions/faint-hope.svg',
        3,
        3,
        0,
        0,
        0,
        0
    ),
    (
        20,
        'Amazement',
        'Combination of Joy and Surprise.',
        '/emotions/amazement.svg',
        3,
        0,
        0,
        0,
        0,
        3
    ),
    (
        21,
        'Disappointment',
        'Combination of Sadness and Surprise.',
        '/emotions/disappointment.svg',
        0,
        3,
        0,
        0,
        0,
        3
    ),
    (
        22,
        'Sternness',
        'Little Anger.',
        '/emotions/sternness.svg',
        0,
        0,
        1,
        0,
        0,
        0
    ),
    (
        23,
        'Indignation',
        'Middling Anger.',
        '/emotions/indignation.svg',
        0,
        0,
        2,
        0,
        0,
        0
    ),
    (
        24,
        'Rage',
        'Heavy Anger.',
        '/emotions/rage.svg',
        0,
        0,
        4,
        0,
        0,
        0
    ),
    (
        25,
        'Disdain',
        'Little Disgust.',
        '/emotions/disdain.svg',
        0,
        0,
        0,
        1,
        0,
        0
    ),
    (
        26,
        'Aversion',
        'Middling Disgust.',
        '/emotions/aversion.svg',
        0,
        0,
        0,
        2,
        0,
        0
    ),
    (
        27,
        'Revulsion',
        'Heavy Disgust.',
        '/emotions/revulsion.svg',
        0,
        0,
        0,
        4,
        0,
        0
    ),
    (
        28,
        'Concern',
        'Little Fear.',
        '/emotions/concern.svg',
        0,
        0,
        0,
        0,
        1,
        0
    ),
    (
        29,
        'Anxiety',
        'Middling Fear.',
        '/emotions/anxiety.svg',
        0,
        0,
        0,
        0,
        2,
        0
    ),
    (
        30,
        'Terror',
        'Heavy Fear.',
        '/emotions/terror.svg',
        0,
        0,
        0,
        0,
        4,
        0
    ),
    (
        31,
        'Satisfaction',
        'Little Joy.',
        '/emotions/satisfaction.svg',
        1,
        0,
        0,
        0,
        0,
        0
    ),
    (
        32,
        'Amusement',
        'Middling Joy.',
        '/emotions/amusement.svg',
        2,
        0,
        0,
        0,
        0,
        0
    ),
    (
        33,
        'Laughter',
        'Heavy Joy.',
        '/emotions/laughter.svg',
        4,
        0,
        0,
        0,
        0,
        0
    ),
    (
        34,
        'Dejection',
        'Little Sadness.',
        '/emotions/dejection.svg',
        0,
        1,
        0,
        0,
        0,
        0
    ),
    (
        35,
        'Melancholy',
        'Middling Sadness.',
        '/emotions/melancholy.svg',
        0,
        2,
        0,
        0,
        0,
        0
    ),
    (
        36,
        'Grief',
        'Heavy Sadness.',
        '/emotions/grief.svg',
        0,
        4,
        0,
        0,
        0,
        0
    ),
    (
        37,
        'Alertness',
        'Little Surprise.',
        '/emotions/alertness.svg',
        0,
        0,
        0,
        0,
        0,
        1
    ),
    (
        38,
        'Wonder',
        'Middling Surprise.',
        '/emotions/wonder.svg',
        0,
        0,
        0,
        0,
        0,
        2
    ),
    (
        39,
        'Shock',
        'Heavy Surprise.',
        '/emotions/shock.svg',
        0,
        0,
        0,
        0,
        0,
        4
    ) ON CONFLICT (id) DO
UPDATE
SET name = excluded.name,
    description = excluded.description,
    icon_url = excluded.icon_url,
    joy = excluded.joy,
    sadness = excluded.sadness,
    anger = excluded.anger,
    disgust = excluded.disgust,
    fear = excluded.fear,
    surprise = excluded.surprise;
alter table emotions
add CONSTRAINT unique_int_rep UNIQUE(joy, anger, disgust, sadness, fear, surprise);
commit TRANSACTION;