application:
  port: 8080
  base_url: "http://localhost"
  hmac_secret: "super-long-and-secret-random-key-needed-to-verify-message-integrity"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "storystains"
redis_uri: "redis://127.0.0.1:6379"
