application:
  port: 8080
  static_files: "./static/root/"
  image_files: "./static/images/"
  host: 0.0.0.0
  exp_token_seconds: 900 # 15 minutes in seconds
database:
  port: 5432
  database_name: "storystains"
  require_ssl: true  
  max_connections: 100