application:
  port: 8080
  host: 0.0.0.0
database:
  port: 5432
  database_name: "storystains"
  require_ssl: true  
  max_connections: 100
frontend:
  static_files: "./static/root/"
  image_files: "./static/images/"
