application:
  host: 127.0.0.1
  static_files: "../frontend/build/web/"
  image_files: "./assets/images/"
  exp_token_seconds: 10
  base_url: "http://localhost"
  hmac_secret: "E1Ta/KyHHCx8V6GAW1CS2/7IkzTkYEIdDL+FlW8N280="
database:
  host: "localhost"
  require_ssl: false
  username: "postgres"
  password: "password"
  max_connections: 10
frontend_origin: "http://localhost:50547"
