application:
  host: 127.0.0.1
  base_url: "http://localhost"
  hmac_secret: "super-long-and-secret-random-key-needed-to-verify-message-integrity"
database:
  host: "localhost"
  require_ssl: false
  username: "postgres"
  password: "password"
  max_connections: 10
frontend:
  origin: "http://localhost:50547"
  static_files: "./static/"
  image_files: "./assets/images/"
redis_uri: "redis://127.0.0.1:6379"
