name: Fly Deploy
concurrency: 
  group: main_deployment
  cancel-in-progress: true
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  DATABASE_URL: ${{ secrets.FLY_DATABASE_URL }}
  SQLX_VERSION: 0.6.0
  SQLX_FEATURES: postgres,native-tls
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3
        - uses: dtolnay/rust-toolchain@stable

        - uses: taiki-e/cache-cargo-install-action@v1
          with:
            tool: sqlx-cli
        
        - name: setup fly
          uses: superfly/flyctl-actions/setup-flyctl@master
        - name: setup proxy to fly db
          run: flyctl proxy 5432 -a storystains-db &
        - name: run migrations
          run: sleep 5 && cd backend && sqlx migrate run && cd ..
        - name: run deploy
          run: flyctl deploy --remote-only
