name: Frontend

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./frontend
jobs:
  flutter-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: pub get
        run: flutter pub get

      - name: build runner
        run: flutter pub run build_runner build

      - name: analyze
        run: flutter analyze

      - name: test
        run: flutter test
  flutter-coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: pub get
        run: flutter pub get

      - name: build runner
        run: flutter pub run build_runner build

      - name: test with coverage
        run: flutter test --coverage
      
      - name: upload to codecov
        uses: codecov/codecov-action@v2
        with:
          flags: flutterfront
          token: ${{secrets.CODECOV_TOKEN}}
  flutter-build-apk:
    name: Apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Checkout
        uses: actions/checkout@v2

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: pub get
        run: flutter pub get

      - name: build runner
        run: flutter pub run build_runner build

      - name: build apk
        run: flutter build apk --release --dart-define BASE_URL="https://app.storystains.com/api"
      
      - name: build appbundle
        run: flutter build appbundle --release --dart-define BASE_URL="https://app.storystains.com/api"

      - uses: actions/upload-artifact@v3
        with:
          # Name of the command/step.
          name: release-apk
          # Path to the release apk.
          path: frontend/build/app/outputs/apk/release/app-release.apk
      
      - uses: actions/upload-artifact@v3
        with:
          # Name of the command/step.
          name: release-appbundle
          # Path to the release apk.
          path: frontend/build/app/outputs/bundle/release/app-release.aab
      