name: Rust

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        working-directory: ./frontend
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'any'
      - run: flutter pub get
      - run: flutter test