name: Frontend

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'any'
      
      - name: pub get
        working-directory: ./frontend
        run: flutter pub get

      - name: test
        working-directory: ./frontend
        run: flutter test