name: Frontend

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'any'
      
      - name: pub get
        working-directory: ./frontend
        run: flutter pub get

      - name: analyze
        working-directory: ./frontend
        run: flutter analyze

      - name: test
        working-directory: ./frontend
        run: flutter test
  flutter-coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'any'
      
      - name: pub get
        working-directory: ./frontend
        run: flutter pub get

      - name: test with coverage
        working-directory: ./frontend
        run: flutter test --coverage
      
      - name: upload to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      